import { QueryProvider } from "@/app/components/providers/query-provider";
import { poppins, raleway } from "@/app/fonts/fonts";
import "@/app/globals.css";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${raleway.variable}`}>
        <QueryProvider>
          <main className="">{children}</main>
        </QueryProvider>
      </body>
    </html>
  );
}
